classification:
  # model:        '/scripts/classifier/model/yolov3-tiny.h5's
  # anchors:      '/scripts/classifier/model/tiny_yolo_anchors.txt'
  model:        '/scripts/classifier/model/YOLOv3-320.h5'
  anchors:      '/scripts/classifier/model/yolo_anchors.txt'
  classes:      '/scripts/classifier/model/coco_classes.txt'

